services:
  postgres:
    image: postgres:16
    container_name: contacts-db
    environment:
      - POSTGRES_DB=contact_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d contact_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: contacts-app
    # Запускать ТОЛЬКО ПОСЛЕ того, как сервис postgres будет "здоров"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contact_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=init

volumes:
  postgres-data: