services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://$DOCKERHOST:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  # --- НАШ НОВЫЙ СЕРВИС ---
  order-service:
    # Указываем Docker собрать образ из папки ../order-service, используя Dockerfile внутри нее
    build: ../order-service
    # Указываем, что этот сервис должен стартовать только ПОСЛЕ того, как запустится kafka
    depends_on:
      - kafka
    # Пробрасываем порт 8080 изнутри контейнера наружу, на порт 8080 вашего компьютера
    ports:
      - "8081:8081"
    # Передаем переменные окружения внутрь контейнера
    environment:
      # ЭТО САМОЕ ВАЖНОЕ:
      # Мы переопределяем настройку из application.properties.
      # Вместо 'localhost:9092', сервис будет подключаться к 'kafka:9092'.
      # 'kafka' - это имя сервиса kafka, которое Docker сам превратит в правильный IP-адрес.
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092