services:
  mysql:
    image: mysql:8.0
    container_name: website-search-engine-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=website_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - website-search-engine-db-data:/var/lib/mysql

  app:
    container_name: website-search-engine
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      # переменная для установки часового пояса
      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/website_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ../logs:/app/logs

volumes:
  website-search-engine-db-data:
